# Generated by Django 3.1.2 on 2020-11-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201114_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('book_title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=200)),
                ('book_type', models.CharField(choices=[('fiction', 'fiction'), ('drama', 'drama'), ('history', 'history'), ('lifestyle', 'lifestyle'), ('children', 'children'), ('college', 'college'), ('biography', 'biography')], max_length=20)),
                ('stock_available', models.IntegerField(default=0)),
            ],
        ),
    ]
