# Generated by Django 3.1.2 on 2020-11-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201117_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
