# Generated by Django 3.1.2 on 2020-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201117_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
